Camd service
zenitheesc/camd pull request #1
Opened 2022-04-13 02:01 UTC by Math-42

Esse pull request cria todo o serviço de câmera, possiblitando chamadas remotas para tirar foto uma rotina de tirar fotos a cada X segundos.

2022-04-13 15:04 UTC, Grillo-0 requested changes

2022-04-13 15:04 UTC, Grillo-0 commented on src/camd.cpp
> +    Daemon camd("camd.json");
onde que está essse arquivo na repo?

2022-04-13 15:04 UTC, Grillo-0 commented on cmake/SourcesAndHeaders.cmake
> +  include/camd/camd.hpp
esse arquivo n existe

2022-04-13 15:04 UTC, Grillo-0 commented on CMakeLists.txt
> +string(APPEND CMAKE_CXX_FLAGS "-lframeworkd -pthread")
não precisa dessa linha

2022-04-13 17:20 UTC, Math-42 commented on src/camd.cpp
> +    Daemon camd("camd.json");
Deveria estar na pasta de config files, já irei subir isso.

2022-04-13 17:24 UTC, Math-42 commented on CMakeLists.txt
> +string(APPEND CMAKE_CXX_FLAGS "-lframeworkd -pthread")
Aparentemente é necessário sim, pelo menos o -pthread.

2022-04-13 17:58 UTC, Grillo-0 commented on CMakeLists.txt
> +string(APPEND CMAKE_CXX_FLAGS "-lframeworkd -pthread")
estranho, aqui retirando essa linha compila certinho

2022-04-13 18:13 UTC, Grillo-0 reviewed
Quando eu tento rodar aqui no note ele da esse erro, no seu PC roda corretamente?

```
[ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/videoio/src/videoio_registry.cpp (217) VideoBackendRegistry VIDEOIO: Enabled backends(8, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); V4L2(970); CV_IMAGES(960); CV_MJPEG(950); FIREWIRE(940); UEYE(930)
[ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/videoio/src/cap_gstreamer.cpp (831) open OpenCV | GStreamer: v4l2src device=/dev/video0 ! videoconvert ! appsink drop=true
[ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/videoio/src/cap_gstreamer.cpp (864) open OpenCV | GStreamer: mode - MANUAL
[ WARN:0] global /builddir/build/BUILD/opencv-4.5.3/modules/videoio/src/cap_gstreamer.cpp (1081) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
terminate called after throwing an instance of 'sdbus::Error'
  what():  [org.freedesktop.DBus.Error.InvalidArgs] Failed to register object vtable (Invalid argument)
fish: Job 1, 'sudo ../build/bin/Debug/camd' terminated by signal SIGABRT (Abort)
```

2022-04-13 18:52 UTC, Math-42 commented
> Quando eu tento rodar aqui no note ele da esse erro, no seu PC roda corretamente?
> 
> ```
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/videoio/src/videoio_registry.cpp (217) VideoBackendRegistry VIDEOIO: Enabled backends(8, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); V4L2(970); CV_IMAGES(960); CV_MJPEG(950); FIREWIRE(940); UEYE(930)
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/videoio/src/cap_gstreamer.cpp (831) open OpenCV | GStreamer: v4l2src device=/dev/video0 ! videoconvert ! appsink drop=true
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/videoio/src/cap_gstreamer.cpp (864) open OpenCV | GStreamer: mode - MANUAL
> [ WARN:0] global /builddir/build/BUILD/opencv-4.5.3/modules/videoio/src/cap_gstreamer.cpp (1081) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
> terminate called after throwing an instance of 'sdbus::Error'
>   what():  [org.freedesktop.DBus.Error.InvalidArgs] Failed to register object vtable (Invalid argument)
> fish: Job 1, 'sudo ../build/bin/Debug/camd' terminated by signal SIGABRT (Abort)
> ```

Sim, roda corretamente.

você instalou o open cv no seu notebook?
Você colocou o arquivo de xml config na pasta correta?
O programa foi inicializado com sudo?

2022-04-14 20:48 UTC, Grillo-0 commented on src/camd.cpp
> +        "zfkd/dbus/camd",
```suggestion
        "/zfkd/dbus/camd",
```
Isso que da o erro previamente demonstrado anteriormente

2022-04-15 13:12 UTC, mairacanal requested changes
No geral, muito bom. Só alguns comentários, principalmente em relação à tratamento de erros.

2022-04-15 13:12 UTC, mairacanal commented on CMakeLists.txt
> +  #    ${PROJECT_NAME}_PROJECT_WARNINGS
Precisa manter esse comentários?

2022-04-15 13:12 UTC, mairacanal commented on src/camd.cpp
> +    int camPhotoDelay = 5000;
Variáveis constantes

2022-04-15 13:12 UTC, mairacanal commented on src/camd.cpp
> +            std::cerr << "ERRO! Camêra inacessível\n";
Não existe nenhuma forma de informar ao framework que essa daemon não funciona?

2022-04-15 13:12 UTC, mairacanal commented on src/camd.cpp
> +        std::string fileName = getFileName();
Variável constante

2022-04-15 13:12 UTC, mairacanal commented on src/camd.cpp
> +            std::cerr << getFileName() + ": ERROR! empty frame \n";
Uma ideia pro frameworkd (caso não esteja ainda implementado): ter uma forma de tratamento de erros.

2022-04-15 13:12 UTC, mairacanal commented on src/camd.cpp
> +        DBusHandler::registerMethod(takePhotoPath, [&](nlohmann::json messaWrapper) {
O que significa `messaWrapper`?

2022-04-15 13:12 UTC, mairacanal commented on src/camd.cpp
> +                takePhoto(messaWrapper["filePath"]);
`takePhoto` não lança nenhuma exceção para ser tratada.

2022-04-18 19:47 UTC, Math-42 commented on src/camd.cpp
> +            std::cerr << "ERRO! Camêra inacessível\n";
Ao framework não.

2022-04-18 19:48 UTC, Math-42 commented on src/camd.cpp
> +        DBusHandler::registerMethod(takePhotoPath, [&](nlohmann::json messaWrapper) {
Message* kkkkk

2022-07-30 07:21 UTC, Grillo-0 approved these changes

2022-07-31 02:14 UTC, merged